### ISSUE TITLE
Recuperar nome do arquivo

### ISSUE THREAD

**Issue by joaofidelix** [giorgiobazzo/horse-upload#1]
Gostaria de tirar uma dúvida sobre o projeto.

Consegui utilizar, rodou legal.
Porém eu gostaria de "interceptar" a requisição.
Depois de fazer o upload gostaria de fazer algum tratamento com o arquivo feito o upload.
Como poderia fazer isto?

Obrigado!

**Comment by giorgiobazzo** [comment]
Ola João, estou em viagem, mas assim que possível vou ver como isso poderia ser feito. Acredito que uma forma seria criar um evento ou callback no TUploadConfig. Como o upload pode conter vários arquivos, esse evento deve dar acesso a um array com as informações dos arquivos para você poder tratar. Quando eu voltar e puder mexer com isso te aviso. Mas também sinta-se a vontade  para enviar um Pull Request. Um abraço!

**Comment by giorgiobazzo** [comment]
Ola João, da uma olhada na versão 1.0.3. Implementei 2 callbacks que irão te ajudar.

**Comment by joaofidelix** [comment]
> Ola João, da uma olhada na versão 1.0.3. Implementei 2 callbacks que irão te ajudar.

Show. Muito bom!!
