### ISSUE TITLE
Horse 2.0

### ISSUE THREAD

**Issue by alcirm** [giorgiobazzo/horse-upload#3]
Não está funcionando com o Horse na versão 2.0.1.

**Comment by giorgiobazzo** [comment]
Desculpa a demora, estava sem tempo de mexer no projeto.

Eu acabei de atualizar para versão 2.0.0 do Horse, pois as ultimas ainda estão em pre-release.

Testei com versão a versão 2.0.0 do Horse e com o Delphi tokyo 10.2. A principio esta ok.

Poderia me informar qual e versão do do Delphi você esta usando?
Poderia também deixar aqui um exemplo de como você esta testando?

**Comment by sergio-api** [comment]
Não está funcionando com a versão 3.0.2 do Horse.
Dá erro nessa linha:
  LWebRequest := THorseHackRequest(Req).GetWebRequest;
Não reconhece o "THorseHackRequest"
Delphi Sidney 10.4.2

**Comment by giorgiobazzo** [comment]
A versão 1.1.0 foi atualizada para horse 3.1.0
