### ISSUE TITLE
Servidor salvando arquivo com o caminho que veio do request.

### ISSUE THREAD

**Issue by ricardowojcik** [giorgiobazzo/horse-upload#4]
Opa... Fiz alguns testes como upload mas me deparei com um problema...
Ao fazer um post pelo delphi 2007 usando o código...

```
var
  IdHTTP: TIdHTTP;
  Params: TIdMultiPartFormDataStream;
  Retorno: string;
  CaminhoArquivo: string;
begin
  Retorno := '';
  IdHTTP := nil;
  Params := nil;
  CaminhoArquivo := 'c:\teste\teste.zip'
  if FileExists(CaminhoArquivo) then
  begin
    Params :=  TIdMultiPartFormDataStream.Create;
    Params.AddFile('file', CaminhoArquivo, '');

    IdHTTP := TIdHTTP.Create(nil);
    IdHTTP.ReadTimeout := 30000;
    IdHTTP.ConnectTimeout := 30000;
    Retorno := IdHTTP.Post('http://127.0.0.1:9000/upload', Params);
    
    FreeAndNil(IdHTTP);
    FreeAndNil(Params);
  end;
```

Mesmo passando a variável `LUploadConfig := TUploadConfig.Create('c:\serverfiles');`
ele está salvando em `c:\teste\teste.zip`

**Comment by giorgiobazzo** [comment]
Ola, Obrigado por mandar o exemplo, desculpa, estava resolvendo outras demandas aqui,

Eu uso a versão Tokyo 10.2, fiz o teste com seu exemplo, e com esta versão esta funcionado corretamente o arquivo teste.zip vai para as pasta c:\serverfiles conforme especificado.
Infelizmente não consigo testar de uma forma rápida na versão 2007, acredito que possa ser alguma coisa com a unit System.IOUtils e a classe TPath que estou usando para montar o caminho de destino, que nessa versão tenha algum detalhe diferente, pois essa unit sofreu muitas mudanças até então.
Você conseguiria debugar o que esta acontecendo na lina 177 do codigo original da unit Horse.Upload.pas?

linha 177:
`LStream := TFileStream.Create(LLocalFilePath, fmCreate);
`
verifique como esta o valor da variável LLocalFilePath, pois é ela que vai determinar onde o arquivo vai ser gravado no servidor.

Também seria interessante verificar como ficou LLocalFilePath após a linha 165:

linha 165:
`LLocalFilePath := TPath.Combine(AConfig.StorePath, LFile.FileName); `

veja se em AConfig.StorePath esta trazendo a pasta de destino do servidor que você determinou.

Se puder fazer isso eu agradeço!

**Comment by ricardowojcik** [comment]
Sim, vamos lá...
Linha 165
`LLocalFilePath := TPath.Combine(AConfig.StorePath, LFile.FileName);`
AConfig.StorePath = 'c:\serverfiles' // o caminho correto que eu informei no LUploadConfig
LFile.FileName = 'c:\teste\teste.zip'// aqui está o problema...
* Eu fiz a correção local substituindo essa linha por:
`LLocalFilePath := TPath.Combine(AConfig.StorePath, ExtractFileName(LFile.FileName));`


Linha 177
`LStream := TFileStream.Create(LLocalFilePath, fmCreate);`
LLocalFilePath = 'c:\teste\teste.zip' // obviamente com problema...

**Comment by giorgiobazzo** [comment]
Muito obrigado pelo feedback, acredito que o problema estava ocorrendo porque o resquest que componente TIdHTTP na versão 2007 do Delphi esteja enviando o caminho completo do arquivo, por isso  LFile.FileName fica como: 'c:\teste\teste.zip'. Na versão Tokyo não estou vendo isso acontecer, LFile.FileName vem sempre como 'teste.zip', independente da pasta que esteja no lado do cliente.
Valeu por detalhar o problema, já subi a correção que você sugeriu para que isso não ocorra mais na versão 1.0.6.
Também adicionei um exemplo usando TIdHTTP semelhante ao que você esta usando.
