### ISSUE TITLE
Usando Horse 3.0.1 Apresenta erro

### ISSUE THREAD

**Issue by FranziniDev** [giorgiobazzo/horse-upload#6]
Como apresentado abaixo. 

[dcc32 Error] Horse.Upload.pas(206): E2003 Undeclared identifier: 'THorseHackRequest'

Existe alguma atualização que corrige ?

**Comment by frankwu-delphi** [comment]
//unit Horse.Upload
//line 199
`procedure Upload(Req: THorseRequest; Res: THorseResponse; Next: TProc);
var
  LWebRequest: TWebRequest;
  LWebResponse: TWebResponse;
  LContent: TObject;
  LUploadConfg : TUploadConfig;
begin
  LWebRequest := Req.RawWebRequest; //THorseHackRequest(Req).GetWebRequest;

  Next;

  LWebResponse := Res.RawWebResponse; //THorseHackResponse(Res).GetWebResponse;
  LContent := Res.Content; //THorseHackResponse(Res).GetContent;

  if Assigned(LContent) and LContent.InheritsFrom(TUploadConfig) then
  begin
    LUploadConfg := TUploadConfig(LContent);
    LWebResponse.Content := ProcessUploads(LWebRequest, LUploadConfg);
    LWebResponse.SendResponse;
  end;
end;`

**Comment by WillmerG** [comment]
thanks [frankwu-delphi](https://github.com/frankwu-delphi) c

**Comment by FranziniDev** [comment]
thanks
